BOOTLOADER = atmel-dfu
EXTRAKEY_ENABLE = yes
PROGRAMMABLE_BUTTON_ENABLE = no
LTO_ENABLE = yes
OS_DETECTION_ENABLE = yes
RGB_MATRIX_ENABLE = no
RGBLIGHT_ENABLE = no
ENCODER_ENABLE = yes
OLED_ENABLE = yes
TAP_DANCE_ENABLE = no
RAW_ENABLE = yes

# Debugging
CONSOLE_ENABLE = no